# Generated by Django 5.2.16 on 2026-08-01 07:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('mission', models.TextField()),
                ('is_synthetic', models.BooleanField(default=True)),
                ('external_execution_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='is_synthetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engagement',
            name='is_synthetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_synthetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='operations.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='operations.company'),
        ),
        migrations.CreateModel(
            name='OperatingCycle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operating_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('report', models.TextField(blank=True)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_cycles', to='operations.company')),
            ],
            options={
                'ordering': ['-operating_date'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField()),
                ('stage', models.CharField(choices=[('discovered', 'Discovered'), ('qualified', 'Qualified'), ('proposed', 'Proposed'), ('won', 'Won'), ('lost', 'Lost')], default='discovered', max_length=20)),
                ('estimated_value_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('probability_percent', models.PositiveSmallIntegerField(default=0)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='operations.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='operations.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='operations.product')),
            ],
            options={
                'ordering': ['-estimated_value_eur'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField()),
                ('title', models.CharField(max_length=240)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('closed', 'Closed')], default='open', max_length=20)),
                ('mitigation', models.TextField(blank=True)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='operations.company')),
            ],
            options={
                'ordering': ['status', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField()),
                ('title', models.CharField(max_length=240)),
                ('function', models.CharField(choices=[('direction', 'Direction'), ('growth', 'Growth'), ('delivery', 'Delivery'), ('finance', 'Finance'), ('operations', 'Operations')], max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('ready', 'Ready'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='proposed', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='operations.company')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionProposal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField()),
                ('action_type', models.SlugField()),
                ('title', models.CharField(max_length=240)),
                ('authority_level', models.PositiveSmallIntegerField(choices=[(0, 'Observe'), (1, 'Draft'), (2, 'Bounded execute'), (3, 'Human approval'), (4, 'Prohibited')])),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('awaiting_approval', 'Awaiting approval'), ('authorized', 'Authorized'), ('simulated', 'Simulated'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='proposed', max_length=30)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_external', models.BooleanField(default=False)),
                ('executor_available', models.BooleanField(default=False)),
                ('outcome', models.JSONField(blank=True, default=dict)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('approval', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_proposal', to='operations.approval')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_proposals', to='operations.company')),
                ('operating_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_proposals', to='operations.operatingcycle')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_proposals', to='operations.workitem')),
            ],
            options={
                'ordering': ['authority_level', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField()),
                ('entry_type', models.CharField(choices=[('revenue', 'Revenue'), ('cost', 'Cost'), ('cash', 'Cash')], max_length=20)),
                ('description', models.CharField(max_length=240)),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('occurred_on', models.DateField()),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='operations.company')),
            ],
            options={
                'ordering': ['-occurred_on'],
                'constraints': [models.UniqueConstraint(fields=('company', 'key'), name='unique_financial_entry_key')],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('paused', 'Paused')], default='active', max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(max_length=40)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='operations.company')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'key'), name='unique_goal_key')],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(max_length=40)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='operations.company')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'key'), name='unique_metric_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='operatingcycle',
            constraint=models.UniqueConstraint(fields=('company', 'operating_date'), name='unique_company_operating_date'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_opportunity_key'),
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_risk_key'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_work_item_key'),
        ),
        migrations.AddConstraint(
            model_name='actionproposal',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_action_proposal_key'),
        ),
    ]
