# Generated by Django 5.2.16 on 2026-08-01 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_company_customer_is_synthetic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='operations.engagement'),
        ),
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_text', models.TextField()),
                ('desired_outcome', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('offered', 'Offer ready'), ('accepted', 'Offer accepted'), ('paid', 'Synthetic payment recorded'), ('in_delivery', 'In delivery'), ('delivered', 'Delivered'), ('revision_requested', 'Revision requested'), ('completed', 'Completed')], default='submitted', max_length=30)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_requests', to='operations.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='operations.customer')),
                ('engagement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_request', to='operations.engagement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_requests', to='operations.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('ready', 'Ready for review'), ('revision_requested', 'Revision requested'), ('accepted', 'Accepted')], default='ready', max_length=30)),
                ('revision_note', models.TextField(blank=True)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('customer_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deliverable', to='operations.customerrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('scope', models.TextField()),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted')], default='proposed', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('customer_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='operations.customerrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyntheticPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(default='internal-simulation', max_length=40)),
                ('external_reference', models.CharField(blank=True, max_length=200)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='operations.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
