# Generated by Django 5.2.16 on 2026-08-01 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_workitem_engagement_customerrequest_deliverable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverable',
            options={'ordering': ['-version']},
        ),
        migrations.AddField(
            model_name='deliverable',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='customer_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='operations.customerrequest'),
        ),
        migrations.AddConstraint(
            model_name='deliverable',
            constraint=models.UniqueConstraint(fields=('customer_request', 'version'), name='unique_deliverable_version'),
        ),
        migrations.AddConstraint(
            model_name='deliverable',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('customer_request',), name='one_current_deliverable_per_request'),
        ),
    ]
