# Generated by Django 5.2.16 on 2026-08-01 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_deliverable_options_deliverable_is_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('cycle_count', models.PositiveSmallIntegerField(default=0)),
                ('report', models.TextField()),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_reports', to='operations.company')),
            ],
            options={
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('company', 'week_start'), name='unique_company_weekly_report')],
            },
        ),
    ]
