# Generated by Django 5.2.16 on 2026-08-02 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_weeklyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loop', models.CharField(choices=[('management', 'Management'), ('operations', 'Operations')], max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('provider', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_eur', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_runs', to='operations.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('rationale', models.TextField()),
                ('function', models.CharField(choices=[('direction', 'Direction'), ('growth', 'Growth'), ('delivery', 'Delivery'), ('finance', 'Finance'), ('operations', 'Operations')], max_length=20)),
                ('evidence', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_decisions', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_suggestion', to='operations.workitem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='operations.suggestionrun')),
            ],
            options={
                'ordering': ['status', 'created_at'],
            },
        ),
    ]
