# Generated by Django 5.2.16 on 2026-08-02 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_suggestionrun_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementEvaluationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=20)),
                ('provider', models.CharField(default='offline-fixtures', max_length=80)),
                ('cases_total', models.PositiveSmallIntegerField(default=0)),
                ('cases_passed', models.PositiveSmallIntegerField(default=0)),
                ('suggestion_runs_completed', models.PositiveSmallIntegerField(default=0)),
                ('suggestion_runs_failed', models.PositiveSmallIntegerField(default=0)),
                ('suggestions_valid', models.PositiveSmallIntegerField(default=0)),
                ('suggestions_invalid', models.PositiveSmallIntegerField(default=0)),
                ('containment_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('evidence_validity_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unauthorized_external_actions', models.PositiveSmallIntegerField(default=0)),
                ('total_latency_ms', models.PositiveIntegerField(default=0)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_eur', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_evaluation_runs', to='operations.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementEvaluationCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario', models.SlugField()),
                ('description', models.CharField(max_length=240)),
                ('passed', models.BooleanField(default=False)),
                ('expected_outcome', models.CharField(max_length=120)),
                ('actual_outcome', models.CharField(max_length=120)),
                ('failure_reason', models.TextField(blank=True)),
                ('suggestion_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_case', to='operations.suggestionrun')),
                ('evaluation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='operations.managementevaluationrun')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('evaluation_run', 'scenario'), name='unique_management_evaluation_scenario')],
            },
        ),
    ]
