# Generated by Django 5.2.16 on 2026-08-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_managementevaluationrun_managementevaluationcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementevaluationrun',
            name='consistency_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='managementevaluationrun',
            name='human_review_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managementevaluationrun',
            name='human_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='managementevaluationrun',
            name='technical_gate_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestionrun',
            name='cost_estimate_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='managementevaluationrun',
            name='status',
            field=models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('needs_review', 'Needs human review')], max_length=20),
        ),
    ]
