# Generated by Django 5.2.16 on 2026-08-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_managementevaluationrun_consistency_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementevaluationrun',
            name='cost_estimate_available',
            field=models.BooleanField(default=False),
        ),
    ]
