# Generated by Django 5.2.16 on 2026-08-02 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_suggestionrun_operating_cycle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDraftRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('provider', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_draft_runs', to='operations.company')),
                ('customer_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_draft_runs', to='operations.customerrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('intent', models.CharField(max_length=40)),
                ('escalation_reason', models.TextField(blank=True)),
                ('evidence', models.JSONField(default=list)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved draft'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_draft_decisions', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='operations.customerdraftrun')),
            ],
            options={
                'ordering': ['status', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEvaluationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('needs_review', 'Needs human review')], max_length=20)),
                ('provider', models.CharField(max_length=80)),
                ('cases_total', models.PositiveSmallIntegerField(default=0)),
                ('cases_passed', models.PositiveSmallIntegerField(default=0)),
                ('drafts_valid', models.PositiveSmallIntegerField(default=0)),
                ('drafts_invalid', models.PositiveSmallIntegerField(default=0)),
                ('evidence_validity_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('consistency_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unauthorized_external_actions', models.PositiveSmallIntegerField(default=0)),
                ('total_latency_ms', models.PositiveIntegerField(default=0)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('technical_gate_passed', models.BooleanField(default=False)),
                ('human_review_completed', models.BooleanField(default=False)),
                ('human_review_note', models.TextField(blank=True)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_evaluation_runs', to='operations.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEvaluationCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario', models.SlugField()),
                ('description', models.CharField(max_length=240)),
                ('passed', models.BooleanField(default=False)),
                ('expected_outcome', models.CharField(max_length=120)),
                ('actual_outcome', models.CharField(max_length=120)),
                ('failure_reason', models.TextField(blank=True)),
                ('draft_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_case', to='operations.customerdraftrun')),
                ('evaluation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='operations.customerevaluationrun')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('evaluation_run', 'scenario'), name='unique_customer_evaluation_scenario')],
            },
        ),
    ]
